settings:
  legacy:
    force: false
    interval: 0s
server:
    status: false               // server status
    open: false                 // open browser at start
    host: localhost             // server host
    port: 3000                  // server port
schema:
- name: squat-backend
  path: .
  commands:
    run:
      status: true
  watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
